# Generated by Django 5.2.12 on 2026-07-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like_comment',
            new_name='likes',
        ),
    ]
